language: python
python:
  - 3.7

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes -q conda -c conda-forge
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

install:
  - conda install -q conda-build pip anaconda-client
  - conda build conda-recipe
  - conda create -n test-env --use-local publish-conda-stack pytest pytest-mock

script:
  - source activate test-env
  - pytest --doctest-modules .
  # test invocation of script
  - publish-conda-stack -h

deploy:
  - provider: script
    script: anaconda -t $CONDA_UPLOAD_TOKEN upload $HOME/miniconda3/conda-bld/**/publish-conda-stack-*.tar.bz2 --label staging --label dev
    on:
      tags: true
    skip_cleanup: true
