channels:
  - conda-forge
dependencies:
  - anaconda-client
  - black
  - boa
  - bumpversion
  - conda-build
  - conda-verify
  - mamba
  - mypy
  - pre_commit
  - pytest
  - pytest-mock
  - ruamel.yaml
