channels:
  - conda-forge
dependencies:
  - anaconda-client
  - argcomplete
  - black
  - bumpversion
  - conda-build >=24.11.0
  - conda-verify
  - mypy
  - pre_commit
  - pytest
  - pytest-mock
  - ruamel.yaml
