{% set data = load_setup_py_data() %}

package:
  name: publish-conda-stack
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  script:
        - python -m pip install --no-deps --ignore-installed .

  entry_points:
    {% for ep in data['entry_points']['console_scripts'] %}
    - {{ ep }}
    {% endfor %}
requirements:
  build:
    - python >=3.6,<3.10
    - pip
  run:
    - python >=3.6,<3.10
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - publish_conda_stack
  source_files:
    - tests
  requires:
    - pytest
    - pytest-mock
  commands:
    - pytest .

about:
  home: https://github.com/ilastik/publish-conda-stack
  author: Stuart E. Berg, Carsten Haubold
  summary: Scripts build a custom set of conda packages from a common environment and publish to a custom conda channel.
  license: MIT
