{% set data = load_setup_py_data() %}

package:
  name: publish-conda-stack
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  script:
        - python -m pip install --no-deps --ignore-installed .
        # not win affects conda build here - package should be built on linux
        # to enable autocomplete in the package
        # This fixes the windows build to enable testing via conda build
        - mkdir -p $PREFIX/etc/conda/activate.d  # [not win]
        - echo 'eval "$(register-python-argcomplete publish-conda-stack -s bash)"' > $PREFIX/etc/conda/activate.d/activate_publish-conda-stack.sh  # [not win]
  entry_points:
    {% for ep in data['entry_points']['console_scripts'] %}
    - {{ ep }}
    {% endfor %}
requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - publish_conda_stack
  source_files:
    - tests
  requires:
    - pytest
    - pytest-mock
  commands:
    - pytest --doctest-modules .

about:
  home: https://github.com/ilastik/publish-conda-stack
  author: Stuart E. Berg, Carsten Haubold
  summary: Scripts build a custom set of conda packages from a common environment and publish to a custom conda channel.
  license: MIT
