name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-w-conda-recipe:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
      - name: install common dependencies
        run: conda install -n base -c conda-forge -c nodefaults conda-build mamba boa -y
      - name: linux conda build test
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: conda mambabuild -c conda-forge conda-recipe
      - name: osx test
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run:  conda mambabuild -c conda-forge conda-recipe
      - name: windows conda-build
        if: matrix.os == 'windows-latest'
        shell: cmd /C CALL {0}
        run: conda mambabuild -c conda-forge conda-recipe
        # HACK: due to a bug in conda-build need to point to
        # libarchive explicitly.
        # https://github.com/conda/conda/issues/12563#issuecomment-1494264704
        env:
          LIBARCHIVE: C:\Miniconda\Library\bin\archive.dll
